-- ================================================================================
-- INSERT statements for Categories (หมวดครุภัณฑ์)
-- ================================================================================

INSERT INTO categories (name) VALUES ('Printer');
INSERT INTO categories (name) VALUES ('S');
INSERT INTO categories (name) VALUES ('W');
INSERT INTO categories (name) VALUES ('กล้องถ่ายรูป');
INSERT INTO categories (name) VALUES ('คอมพิวเตอร์');
INSERT INTO categories (name) VALUES ('ฉายภาพ');
INSERT INTO categories (name) VALUES ('ตู้เก็บเอกสาร');
INSERT INTO categories (name) VALUES ('ตู้เย็น , ถังต้มน้ำไฟฟ้า');
INSERT INTO categories (name) VALUES ('ปรับสมุด');
INSERT INTO categories (name) VALUES ('รถเข็น');
INSERT INTO categories (name) VALUES ('สแกน');
INSERT INTO categories (name) VALUES ('สแกนลายนิ้วมือ');
INSERT INTO categories (name) VALUES ('อื่นๆ');
INSERT INTO categories (name) VALUES ('เก้าอี้');
INSERT INTO categories (name) VALUES ('เครื่องนับ');
INSERT INTO categories (name) VALUES ('เครื่องพับ');
INSERT INTO categories (name) VALUES ('เครื่องฟอกอากาศ');
INSERT INTO categories (name) VALUES ('เครื่องเสียง');
INSERT INTO categories (name) VALUES ('เน็ตเวิร์ค');
INSERT INTO categories (name) VALUES ('แท็ปเล็ต');
INSERT INTO categories (name) VALUES ('แฟกซ์');
INSERT INTO categories (name) VALUES ('แอร์');
INSERT INTO categories (name) VALUES ('โต๊ะ');
INSERT INTO categories (name) VALUES ('โน๊ตบุค');

-- Total: 24 categories


-- ================================================================================
-- INSERT statements for Assets (ข้อมูลครุภัณฑ์)
-- ================================================================================

INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A004-09-04-2557', 'HP ENVY TOUCH SMART 20-d106d ดำ', 'HP', 'ดำ', '5CM40301SS', 26990.00, 'ห้อง IT', 'Normal', '2014-04-09', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A010-09-04-2557', 'HP ENVY TOUCH SMART 20-d106d ดำ', 'HP', 'ดำ', '5CM40301X1', 26990.00, 'ห้อง IT', 'Normal', '2014-04-09', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A018-03-03-2559', 'DELL U2515H ดำ', 'DELL', 'ดำ', 'CN-001N56-64180-5CG-00FL-A02', 14500.00, 'ฝ่ายอำนวยการ(คุณสุภาพร)', 'Normal', '2016-03-03', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A019-03-03-2559', 'DELL U2515H ดำ', 'DELL', 'ดำ', 'CN-001N56-64180-5CG-04KL-A02', 14500.00, 'ฝ่าย IT (คุณสมัย)', 'Normal', '2016-03-03', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A020-31-03-2559', 'ELO 2201L ดำ', 'ELO', 'ดำ', 'G153000653', 20000.00, 'จุดบริการตู้ ATM', 'Normal', '2016-03-31', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A021-18-08-2559', 'HP Pavilion All-in-One 23-q130d ดำ-ขาว', 'HP', 'ดำ-ขาว', '8CC60503DR', 32410.00, 'ห้อง IT *ไม่ได้ใช้งาน*', 'Normal', '2016-08-18', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A022-18-08-2559', 'HP Pavilion All-in-One 23-q130d ดำ-ขาว', 'HP', 'ดำ-ขาว', '8CC60507GH', 32410.00, 'ห้อง IT *ไม่ได้ใช้งาน*', 'Normal', '2016-08-18', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A023-18-08-2559', 'HP Pavilion All-in-One 23-q130d ดำ-ขาว', 'HP', 'ดำ-ขาว', '8CC60507PR', 32410.00, 'ห้องกรรมการ (คุณสหัส)', 'Normal', '2016-08-18', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A024-18-08-2559', 'HP Pavilion All-in-One 23-q130d ดำ-ขาว', 'HP', 'ดำ-ขาว', '8CC60503DG', 32410.00, 'ห้องรองประธาน/เลขานุการ โต๊ะ 1', 'Normal', '2016-08-18', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A025-18-08-2559', 'HP Pavilion All-in-One 23-q130d ดำ-ขาว', 'HP', 'ดำ-ขาว', '8CC60503DD', 32410.00, 'กพส.(คุณพงศ์พันธ์)', 'Normal', '2016-08-18', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A026-18-08-2559', 'HP Pavilion All-in-One 23-q130d ดำ-ขาว', 'HP', 'ดำ-ขาว', '8CC60503DM', 32410.00, 'ห้องกรรมการ(คุณสรัญญา)', 'Normal', '2016-08-18', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A027-18-08-2559', 'HP Pavilion All-in-One 23-q130d ดำ-ขาว', 'HP', 'ดำ-ขาว', '8CC60503DJ', 32410.00, 'ฝ่ายอำนวยการ(คุณอรรถชัย)', 'Normal', '2016-08-18', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A028-18-08-2559', 'HP Pavilion All-in-One 23-q130d ดำ-ขาว', 'HP', 'ดำ-ขาว', '8CC60503DV', 32410.00, 'ห้องกรรมการ(อ.รังสรรค์)', 'Normal', '2016-08-18', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A029-18-08-2559', 'HP Pavilion All-in-One 23-q130d ดำ-ขาว', 'HP', 'ดำ-ขาว', '8CC60503D4', 32410.00, 'วิทยาเขตศรีราชา', 'Normal', '2016-08-18', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A030-18-08-2559', 'HP Pavilion All-in-One 23-q130d ดำ-ขาว', 'HP', 'ดำ-ขาว', '8CC60503FO', 32410.00, 'วิทยาเขตสกลนคร', 'Normal', '2016-08-18', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A031-26-12-2560', 'DELL Inspiron One 3264 Touch Screen ดำ', 'DELL', 'ดำ', 'C243ZH2', 28900.00, 'ห้องข้างผู้ช่วยฯ สุชญา(ใช้ดูตารางประชุม)', 'Normal', '2017-12-26', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A032-13-07-2561', 'DELL Inspiron One 24 3477 ดำ', 'DELL', 'ดำ', '9CFWL42', 30281.00, 'ห้อง IT *ไม่ได้ใช้งาน*', 'Normal', '2018-07-13', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A033-13-07-2561', 'DELL Inspiron One 24 3477 ดำ', 'DELL', 'ดำ', '4Q36902', 30281.00, 'ห้อง IT *ซื้อเครื่องใหม่ทดแทนแล้ว*', 'Normal', '2018-07-13', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A034-13-07-2561', 'DELL Inspiron One 24 3477 ดำ', 'DELL', 'ดำ', '68X7L42', 30281.00, 'เคาน์เตอร์ 13', 'Normal', '2018-07-13', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A035-13-07-2561', 'DELL Inspiron One 24 3477 ดำ', 'DELL', 'ดำ', 'CMFWL42', 30281.00, 'ห้อง IT *ซื้อเครื่องใหม่ทดแทนแล้ว*', 'Normal', '2018-07-13', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A036-13-07-2561', 'DELL Inspiron One 24 3477 ดำ', 'DELL', 'ดำ', '79X7L42', 30281.00, 'ห้อง IT *ซื้อเครื่องใหม่ทดแทนแล้ว*', 'Normal', '2018-07-13', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A037-13-07-2561', 'DELL Inspiron One 24 3477 ดำ', 'DELL', 'ดำ', 'FKFWL42', 30281.00, 'ห้อง IT *ซื้อเครื่องใหม่ทดแทนแล้ว*', 'Normal', '2018-07-13', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A038-08-08-2561', 'DELL Inspiron One 24 3477 ดำ', 'DELL', 'ดำ', '82JRL42', 30281.00, 'ห้อง IT *ซื้อเครื่องใหม่ทดแทนแล้ว*', 'Normal', '2018-08-08', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A039-08-08-2561', 'DELL Inspiron One 24 3477 ดำ', 'DELL', 'ดำ', 'F2JRL42', 30281.00, 'ห้อง IT *ซื้อเครื่องใหม่ทดแทนแล้ว*', 'Normal', '2018-08-08', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A040-08-08-2561', 'DELL Inspiron One 24 3477 ดำ', 'DELL', 'ดำ', '7PFWL42', 30281.00, 'ห้อง IT *ซื้อเครื่องใหม่ทดแทนแล้ว*', 'Normal', '2018-08-08', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A041-08-08-2561', 'DELL Inspiron One 24 3477 ดำ', 'DELL', 'ดำ', 'C2JRL42', 30281.00, 'ห้อง IT *ซื้อเครื่องใหม่ทดแทนแล้ว*', 'Normal', '2018-08-08', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A042-08-08-2561', 'DELL Inspiron One 24 3477 ดำ', 'DELL', 'ดำ', '5KFWL42', 30281.00, 'ห้อง IT *ซื้อเครื่องใหม่ทดแทนแล้ว*', 'Normal', '2018-08-08', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A043-08-08-2561', 'DELL Inspiron One 24 3477 ดำ', 'DELL', 'ดำ', 'DJ7WL42', 30281.00, 'ห้อง IT *ซื้อเครื่องใหม่ทดแทนแล้ว*', 'Normal', '2018-08-08', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A044-06-09-2561', 'DELL Inspiron One 24 3477 ดำ', 'DELL', 'ดำ', '7936902', 30281.00, 'ห้อง IT *ซื้อเครื่องใหม่ทดแทนแล้ว*', 'Normal', '2018-09-06', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A045-06-09-2561', 'DELL Inspiron One 24 3477 ดำ', 'DELL', 'ดำ', '6HFWL42', 30281.00, 'ห้อง IT *ซื้อเครื่องใหม่ทดแทนแล้ว*', 'Normal', '2018-09-06', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A046-06-09-2561', 'DELL Inspiron One 24 3477 ดำ', 'DELL', 'ดำ', 'D8X7L42', 30281.00, 'ห้อง IT *ซื้อเครื่องใหม่ทดแทนแล้ว*', 'Normal', '2018-09-06', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A047-12-09-2561', 'HPE ProLiant DL380 Gen 9 เงิน', 'HPE ProLiant', 'เงิน', 'CN775206WC', 299600.00, 'DC สบค.', 'Normal', '2018-09-12', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A049-11-04-2562', 'COMPONENT COMPONENT Smart Card ดำ', 'COMPONENT', 'ดำ', '-', 8500.00, 'ฝ่ายอำนวยการ', 'Normal', '2019-04-11', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A050-12-09-2562', 'DELL PowerEdge R740 เงิน', 'DELL', 'เงิน', 'C915HY2', 293073.00, 'ฝ่าย IT', 'Normal', '2562-09-12', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A051-17-10-2562', 'DELL OptiPlex 5270 AIO ดำ', 'DELL', 'ดำ', '518FRZ3', 35845.00, 'ห้องรองฯ 1(อ.บพิธ)', 'Normal', '2562-10-17', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A052-17-10-2562', 'DELL OptiPlex 5270 AIO ดำ', 'DELL', 'ดำ', '518FRZ2', 35845.00, 'ห้องกรรมการ(คุณสมนึก)', 'Normal', '2562-10-17', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A053-17-10-2562', 'DELL OptiPlex 5270 AIO ดำ', 'DELL', 'ดำ', '519FRZ2', 35845.00, 'คุณวชิราพร โต๊ะสินเชื่อ', 'Normal', '2562-10-17', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A054-17-10-2562', 'DELL OptiPlex 5270 AIO ดำ', 'DELL', 'ดำ', '518LRZ2', 35845.00, 'ห้องกรรมการ(อ.วัลลภ)', 'Normal', '2562-10-17', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A055-17-10-2562', 'DELL OptiPlex 5270 AIO ดำ', 'DELL', 'ดำ', '518JRZ2', 35845.00, 'ฝ่ายลงทุน(คุณปฐมพงศ์)', 'Normal', '2562-10-17', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A056-17-10-2562', 'DELL OptiPlex 5270 AIO ดำ', 'DELL', 'ดำ', '517LRZ2', 35845.00, 'กพส.(คุณอรพรรณ)', 'Normal', '2562-10-17', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A057-17-10-2562', 'DELL OptiPlex 5270 AIO ดำ', 'DELL', 'ดำ', '519DRZ2', 35845.00, 'กพส.(คุณณัฐชยา)', 'Normal', '2562-10-17', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A058-11-12-2562', 'DELL Optiplex 3070 Micro ดำ', 'DELL', 'ดำ', 'JZ2N6Z2', 12305.00, 'เครื่องคิว(ข้างเคาน์เตอร์ 5)', 'Normal', '2562-12-11', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A059-27-12-2562', 'Polycom Group 500 เงิน', 'Polycom', 'เงิน', '8G19124CCC3CCV', 269961.00, 'ห้องประชุมชั้น 1', 'Normal', '2562-12-27', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A060-24-04-2563', 'HPE ProLiant DL380 Gen 10 เงิน', 'HPE ProLiant', 'เงิน', 'SGH944S00R', 337050.00, 'ห้อง IT', 'Normal', '2563-04-24', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A061-06-11-2563', 'Synology RS2418+ ดำ', 'Synology', 'ดำ', '2080P9N158600', 159644.00, 'ห้อง IT', 'Normal', '2563-11-06', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A062-15-03-2564', 'DELL U270Q ดำ', 'DELL', 'ดำ', '8XX8C23', 18725.00, 'ห้อง IT (คุณตุลภัทร)', 'Normal', '2564-03-15', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A063-23-07-2564', 'DELL 7090 Micro ดำ', 'DELL', 'ดำ', 'J36PQF3', 33865.50, 'เคาน์เตอร์ 2', 'Normal', '2021-06-23', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A064-23-07-2564', 'DELL 7090 Micro ดำ', 'DELL', 'ดำ', 'F46PQF3', 33865.50, 'เคาน์เตอร์ 4', 'Normal', '2021-06-23', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('.A065-23-07-2564', 'DELL 7090 Micro ดำ', 'DELL', 'ดำ', '646PQF3', 33865.50, 'เคาน์เตอร์ 11', 'Normal', '2021-06-23', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A066-23-07-2564', 'DELL 7090 Micro ดำ', 'DELL', 'ดำ', 'D46PQF3', 33865.50, 'เคาน์เตอร์ 5', 'Normal', '2021-06-23', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A067-23-07-2564', 'DELL 7090 Micro ดำ', 'DELL', 'ดำ', 'C46PQF3', 33865.50, 'ฝ่ายบัญชี(คุณพุทธวรรณ)', 'Normal', '2021-06-23', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A068-23-07-2564', 'DELL 7090 Micro ดำ', 'DELL', 'ดำ', 'B46PQF3', 33865.50, 'ฝ่ายสินเชื่อ(คุณพงษ์ศักดิ์)', 'Normal', '2021-06-23', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A069-23-07-2564', 'DELL 7090 Micro ดำ', 'DELL', 'ดำ', '146PQF3', 33865.50, 'เคาน์เตอร์ 7', 'Normal', '2021-06-23', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A070-23-07-2564', 'DELL 7090 Micro ดำ', 'DELL', 'ดำ', '846PQF3', 33865.50, 'เคาน์เตอร์ 8', 'Normal', '2021-06-23', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A071-23-07-2564', 'DELL 7090 Micro ดำ', 'DELL', 'ดำ', '746PQF3', 33865.50, 'เคาน์เตอร์ 6', 'Normal', '2021-06-23', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A072-23-07-2564', 'DELL 7090 Micro ดำ', 'DELL', 'ดำ', 'G46PQF3', 33865.50, 'เคาน์เตอร์ 3', 'Normal', '2021-06-23', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A073-23-07-2564', 'DELL 7090 Micro ดำ', 'DELL', 'ดำ', '546PQF3', 33865.50, 'ฝ่ายอำนวยการ (คุณสุภาพร)', 'Normal', '2021-06-23', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A074-23-07-2564', 'DELL 7090 Micro ดำ', 'DELL', 'ดำ', '446PQF3', 33865.50, 'ฝ่ายอำนวยการ (คุณณัชชา)', 'Normal', '2021-06-23', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A075-23-07-2564', 'DELL 7090 Micro ดำ', 'DELL', 'ดำ', '346PQF3', 33865.50, 'เคาน์เตอร์ 10', 'Normal', '2021-06-23', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A076-23-07-2564', 'DELL 7090 Micro ดำ', 'DELL', 'ดำ', '246PQF3', 33865.50, 'ฝ่ายอำนวยการ (คุณวชิราพร) คอม', 'Normal', '2021-06-23', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A077-23-07-2564', 'DELL 7090 Micro ดำ', 'DELL', 'ดำ', '946PQF3', 33865.50, 'เคาน์เตอร์ 12', 'Normal', '2021-06-23', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A078-23-07-2564', 'DELL 7090 Micro ดำ', 'DELL', 'ดำ', 'H46PQF3', 33865.50, 'เคาน์เตอร์ 1', 'Normal', '2021-06-23', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A079-23-07-2564', 'DELL 7090 Micro ดำ', 'DELL', 'ดำ', 'H36PQF3', 33865.50, 'ฝ่ายการเงิน (คุณสุรัตน์)', 'Normal', '2021-06-23', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A080-00-00-0000', 'APC SU48RMX ดำ', 'APC', 'ดำ', 'SGS02351425901', 0.00, 'ฝ่าย IT', 'Normal', NULL, 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A081-00-00-0000', 'APC SU48RMX ดำ', 'APC', 'ดำ', 'SGS0235142586', 0.00, 'ฝ่าย IT', 'Normal', NULL, 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A082-00-00-0000', 'APC SU3000RMX ดำ', 'APC', 'ดำ', 'SGS0234171062', 0.00, 'ฝ่าย IT', 'Normal', NULL, 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A083-28-11-2565', 'APC Smart-UPS 1500VA LCD RM 2U 230V ดำ', 'APC', 'ดำ', 'AS2210260348', 20865.00, 'กพส.', 'Normal', '2565-11-28', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A084-23-02-2566', 'Lenovo ThinkCentre Neo 50t Gen 3 ดำ', 'Lenovo', 'ดำ', 'PC2L6SS2', 21614.00, 'กพส.', 'Normal', '2566-02-22', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A085-23-02-2566', 'Lenovo ThinkCentre Neo 50t Gen 3 ดำ', 'Lenovo', 'ดำ', 'PC2L6STY', 21614.00, 'ห้องพิมพ์ใบเสร็จ', 'Normal', '2566-02-23', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A086-20-03-2566', 'Lenovo Thinkpad E15 Gen 4 ดำ', 'Lenovo', 'ดำ', 'PF48RCQZ', 37664.00, 'ฝ่ายการลงทุน (คุณณัฎฐเวช)', 'Normal', '2566-03-20', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A087-20-03-2566', 'Lenovo Thinkpad E15 Gen 4 ดำ', 'Lenovo', 'ดำ', 'SPF48R1EX', 37664.00, 'ฝ่ายบัญชี (คุณธัญญ์ศริน)', 'Normal', '2566-03-20', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A088-20-03-2566', 'Lenovo Thinkpad E15 Gen 4 ดำ', 'Lenovo', 'ดำ', NULL, 37664.00, 'ผู้จัดการ(คุณปิยธิดา)', 'Normal', '2566-03-20', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A089-20-03-2566', 'DELL U2722DE เงิน', 'DELL', 'เงิน', '47MLZN3', 15087.00, 'ฝ่ายการลงทุน(คุณณัฎฐเวช)', 'Normal', '2566-03-20', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A090-20-03-2566', 'DELL U2722DE เงิน', 'DELL', 'เงิน', '28MLZN3', 15087.00, 'ฝ่ายบัญชี(คุณธัญญ์ศริน)', 'Normal', '2566-03-20', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A091-20-03-2566', 'DELL U2722DE เงิน', 'DELL', 'เงิน', '3WHJYN3', 15087.00, 'ผู้จัดการ(คุณปิยธิดา)', 'Normal', '2566-03-20', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A092-19-02-2567', 'DELL U2723QE เงิน', 'DELL', 'เงิน', 'G3S9BP3', 17974.93, 'ฝ่าย IT (คุณเกียรติณรงค์)', 'Normal', '2567-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A093-19-02-2567', 'DELL U2723QE เงิน', 'DELL', 'เงิน', 'J4S9BP3', 17974.93, 'ฝ่าย IT (คุณสมัย)', 'Normal', '2567-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A094-19-02-2567', 'DELL U2723QE เงิน', 'DELL', 'เงิน', '71FLCP3', 17974.93, 'ฝ่าย IT (คุณกัญหา)', 'Normal', '2567-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A095-20-03-2567', 'DELL SFF 7010 ดำ', 'DELL', 'ดำ', 'B4KG824', 28500.52, 'ฝ่ายอำนวยการ(คุณชนิกานต์) คอม', 'Normal', '2567-03-20', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A096-20-03-2567', 'DELL SFF 7010 ดำ', 'DELL', 'ดำ', '74KG824', 28500.52, 'ฝ่ายอำนวยการ(คุณพัทรดา) คอม', 'Normal', '2567-03-20', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A097-29-03-2567', 'DELL SFF 7010 ดำ', 'DELL', 'ดำ', '94KG824', 28500.52, 'ฝ่ายการเงิน(คุณจิราพร) คอม', 'Normal', '2567-03-20', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A098-29-03-2567', 'DELL SFF 7010 ดำ', 'DELL', 'ดำ', '54KG824', 28500.52, 'ฝ่ายสินเชื่อ(คุณธนาเทพ) คอม', 'Normal', '2567-03-20', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A099-29-03-2567', 'DELL SFF 7010 ดำ', 'DELL', 'ดำ', '64KG824', 28500.52, 'ฝ่ายสินเชื่อ(คุณธมลวรรณ) คอม', 'Normal', '2567-03-20', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A100-29-03-2567', 'DELL SFF 7010 ดำ', 'DELL', 'ดำ', '84KH824', 28500.52, 'ฝ่ายบัญชี(คุณขวัญฤทัย) คอม', 'Normal', '2567-03-20', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A101-29-03-2567', 'DELL P2422H เงิน', 'DELL', 'เงิน', '2ZOT714', 5890.35, 'ฝ่ายอำนวยการ(คุณภัทรดา) จอ', 'Normal', '2567-03-20', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A102-29-03-2567', 'DELL P2422H เงิน', 'DELL', 'เงิน', '2KLT714', 5890.35, 'ฝ่ายการเงิน(คุณจิราพร) จอ', 'Normal', '2567-03-20', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A103-29-03-2567', 'DELL P2422H เงิน', 'DELL', 'เงิน', '31LT714', 5890.35, 'ฝ่ายสินเชื่อ(คุณธนาเทพ) จอ', 'Normal', '2567-03-20', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A104-29-03-2567', 'DELL P2422H เงิน', 'DELL', 'เงิน', '33LT714', 5890.35, 'ฝ่ายสินเชื่อ(คุณธมลวรรณ) จอ', 'Normal', '2567-03-20', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A105-29-03-2567', 'DELL P2422H เงิน', 'DELL', 'เงิน', '2ZZT714', 5890.35, 'ฝ่ายบัญชี(คุณขวัญฤทัย) จอ', 'Normal', '2567-03-20', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A106-29-03-2567', 'DELL P2422H เงิน', 'DELL', 'เงิน', '33OV714', 5890.35, 'ฝ่ายอำนวยการ(คุณชนิกานต์) จอ', 'Normal', '2567-03-20', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A107-20-09-2567', 'DELL PowerEdge R760 เงิน', 'DELL', 'เงิน', 'BXW2564', 349569.00, 'Data Center สบค.', 'Normal', '2567-09-20', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A108-12-12-2567', 'DELL P2425HE เงิน', 'DELL', 'เงิน', '9N6NK34', 8142.70, 'ฝ่ายอำนวยการ(คุณวชิราพร) จอ', 'Normal', '2567-12-12', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A109-19-02-2568', 'DELL SFF 7020 ดำ', 'DELL', 'ดำ', '2Y4MN54', 31602.45, 'รองผู้จัดการ(คุณอุราพร) คอม', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A110-19-02-2568', 'DELL SFF 7020 ดำ', 'DELL', 'ดำ', '2X4MN54', 31602.45, 'ฝ่ายสินเชื่อ(คุณวรินทร์ธร) คอม', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A111-19-02-2568', 'DELL SFF 7020 ดำ', 'DELL', 'ดำ', 'FP98P54', 31602.45, 'ฝ่ายอำนวยการ(คุณพรภิชัย) คอม', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A112-19-02-2568', 'DELL SFF 7020 ดำ', 'DELL', 'ดำ', '3R98P54', 31602.45, 'ฝ่ายอำนวยการ(คุณพรพิมล) คอม', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A113-19-02-2568', 'DELL SFF 7020 ดำ', 'DELL', 'ดำ', 'FY4MN54', 31602.45, 'หัวหน้าสินเชื่อ(คุณชวาลา) คอม', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A114-19-02-2568', 'DELL SFF 7020 ดำ', 'DELL', 'ดำ', 'HP98P54', 31602.45, 'หัวหน้าอำนวยการ(คุณสดใส) คอม', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A115-19-02-2568', 'DELL SFF 7020 ดำ', 'DELL', 'ดำ', '9Y4MN54', 31602.45, 'ฝ่ายอำนวยการ(คุณศศิภา) คอม', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A116-19-02-2568', 'DELL SFF 7020 ดำ', 'DELL', 'ดำ', '8Q98P54', 31602.45, 'ฝ่ายการเงิน(คุณวรพร) คอม', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A117-19-02-2568', 'DELL SFF 7020 ดำ', 'DELL', 'ดำ', '2P98P54', 31602.45, 'ผู้ช่วยผู้จัดการ(คุณสุชญา) คอม', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A118-19-02-2568', 'DELL SFF 7020 ดำ', 'DELL', 'ดำ', '7Q98P54', 31602.45, 'ฝ่ายสินเชื่อ(คุณวชิรวิทย์) คอม', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A119-19-02-2568', 'DELL SFF 7020 ดำ', 'DELL', 'ดำ', 'GW4MN54', 31602.45, 'หัวหน้าการเงิน(คุณพรชนัน) คอม', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A120-19-02-2568', 'DELL SFF 7020 ดำ', 'DELL', 'ดำ', 'HY4MN54', 31602.45, 'ผู้ช่วยผู้จัดการ(คุณธัญญา) คอม', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A121-19-02-2568', 'DELL SFF 7020 ดำ', 'DELL', 'ดำ', 'DQ98P54', 31602.45, 'กพส.(คุณธมนวรรณ) คอม', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A122-19-02-2568', 'DELL P2425H ดำ', 'DELL', 'ดำ', '93RYK34', 5885.00, 'หัวหน้าอำนวยการ(คุณสดใส) จอ', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A123-19-02-2568', 'DELL P2425H ดำ', 'DELL', 'ดำ', '93TWK34', 5885.00, 'ผู้ช่วยผู้จัดการ(คุณธัญญา) จอ', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A124-19-02-2568', 'DELL P2425H ดำ', 'DELL', 'ดำ', '96TWK34', 5885.00, 'รองผู้จัดการ(คุณอุราพร) จอ', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A125-19-02-2568', 'DELL P2425H ดำ', 'DELL', 'ดำ', 'B2TRK34', 5885.00, 'หัวหน้าการเงิน(คุณพรชนัน) จอ', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A126-19-02-2568', 'DELL P2425H ดำ', 'DELL', 'ดำ', '90Y1L34', 5885.00, 'ฝ่ายการเงิน(คุณวรพร) จอ', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A127-19-02-2568', 'DELL P2425H ดำ', 'DELL', 'ดำ', '96LWK34', 5885.00, 'ฝ่ายสินเชื่อ(คุณวชิรวิทย์) จอ', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A128-19-02-2568', 'DELL P2425H ดำ', 'DELL', 'ดำ', '950RK34', 5885.00, 'ฝ่ายสินเชื่อ(คุณวรินทร์ธร) จอ', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A129-19-02-2568', 'DELL P2425H ดำ', 'DELL', 'ดำ', '953WK34', 5885.00, 'ผู้ช่วยผู้จัดการ(คุณสุชญา) จอ', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A130-19-02-2568', 'DELL P2425H ดำ', 'DELL', 'ดำ', 'B2M0L34', 5885.00, 'ฝ่ายอำนวยการ(คุณพรพิมล) จอ', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A131-19-02-2568', 'DELL P2425H ดำ', 'DELL', 'ดำ', '93RQK34', 5885.00, 'ฝ่ายอำนวยการ(คุณพรภิชัย) จอ', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A132-19-02-2568', 'DELL P2425H ดำ', 'DELL', 'ดำ', 'B2VRK34', 5885.00, 'ฝ่ายอำนวยการ(คุณศศิภา) จอ', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A133-19-02-2568', 'DELL P2425H ดำ', 'DELL', 'ดำ', 'B2VXK34', 5885.00, 'ฝ่ายอำนวยการ(คุณพรภิชัย) จอ', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A134-19-02-2568', 'DELL P2425H ดำ', 'DELL', 'ดำ', '9DY0L34', 5885.00, 'กพส.(คุณธมนวรรณ) จอ', 'Normal', '2568-02-19', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A135-26-06-2568', 'DELL 7020 Micro ดำ', 'DELL', 'ดำ', NULL, 14338.00, 'คอมฯประชาสัมพันธ์ กำแพงแสน', 'Normal', '2568-06-26', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('A136-25-07-2568', 'vertive liebert 10kva ดำ', 'vertive', 'ดำ', NULL, 698074.00, 'ห้องสำรองไฟฟ้าชั้น 2 (แบตเตอรี่ 40 ลูก)', 'Normal', '2568-07-25', 'คอมพิวเตอร์', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;
INSERT INTO assets (code, name, brand, color, serial, price, location, status, purchase_date, category, useful_life) VALUES ('239780', 'โต๊ะประชุม', NULL, 'โต๊ะประชุม', '139017.68', 0.00, 'ห้องประชุมชั้น 2', 'Normal', NULL, 'โต๊ะ', 5) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, brand = EXCLUDED.brand, color = EXCLUDED.color, serial = EXCLUDED.serial, price = EXCLUDED.price, location = EXCLUDED.location, status = EXCLUDED.status, purchase_date = EXCLUDED.purchase_date, category = EXCLUDED.category, useful_life = EXCLUDED.useful_life;

-- Total: 121 assets

-- ================================================================================
-- Summary
-- ================================================================================
-- Categories: 24
-- Assets: 123
-- ================================================================================